language: node_js
node_js:
  - "5.11"
env:
  - CXX=g++-4.8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  firefox: "45.0"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
